// Code generated by goctl. DO NOT EDIT.
// Source: demo2.proto

package server

import (
	"context"

	"demo2/internal/logic"
	"demo2/internal/svc"
	"demo2/proto"
)

type Demo2Server struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedDemo2Server
}

func NewDemo2Server(svcCtx *svc.ServiceContext) *Demo2Server {
	return &Demo2Server{
		svcCtx: svcCtx,
	}
}

func (s *Demo2Server) Ping(ctx context.Context, in *proto.Request) (*proto.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *Demo2Server) GetEmpty(ctx context.Context, in *proto.EmptyReq) (*proto.EmptyResp, error) {
	l := logic.NewGetEmptyLogic(ctx, s.svcCtx)
	return l.GetEmpty(in)
}
